CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UtilisateurId UNIQUEIDENTIFIER NOT NULL,
    Titre NVARCHAR(MAX) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Type NVARCHAR(MAX) NOT NULL,
    Canaux NVARCHAR(MAX) NOT NULL,
    Statut NVARCHAR(MAX) NOT NULL,
    DateEnvoi DATETIME2 NOT NULL,
    DateLecture DATETIME2 NULL
);

CREATE TABLE Preferences (
    UtilisateurId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RecevoirEmail BIT NOT NULL,
    RecevoirSms BIT NOT NULL,
    RecevoirInApp BIT NOT NULL,
    Langue NVARCHAR(MAX) NOT NULL
);
