stages:
  - build
  - test
  - docker
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOCKER_REGISTRY: "$CI_REGISTRY/saas-clinic"
  DOCKER_IMAGE_TAG: "latest"

# ---------------- Build .NET projects ----------------
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - |
      for sln in Services/*/*.sln; do
        echo "Restoring and building $sln..."
        dotnet restore "$sln"
        dotnet build "$sln" --configuration Release
      done

# ---------------- Run tests ----------------
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - |
      for sln in Services/*/*.sln; do
        echo "Running tests for $sln..."
        dotnet test "$sln" --no-build --verbosity normal || exit 1
      done

# ---------------- Build & Push Docker images ----------------
docker_build_backend:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: "registry.gitlab.com/AyoubDammak/clinic-saas"
    DOCKER_IMAGE_TAG: "latest"
  script:
    - apk add --no-cache bash
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      bash -c '
        services=("AuthService" "ClinicManagementService" "DoctorManagementService" "PatientManagementService" "RDVManagementService" "ConsultationManagementService" "FacturationService" "ReportingService" "NotificationService")

        for service in "${services[@]}"; do
          if [ "$service" = "AuthService" ]; then dockerfile="Auth.API/Dockerfile"; fi
          if [ "$service" = "ClinicManagementService" ]; then dockerfile="Clinic.API/Dockerfile"; fi
          if [ "$service" = "DoctorManagementService" ]; then dockerfile="Doctor.API/Dockerfile"; fi
          if [ "$service" = "PatientManagementService" ]; then dockerfile="PatientManagementService.API/Dockerfile"; fi
          if [ "$service" = "RDVManagementService" ]; then dockerfile="RDV.API/Dockerfile"; fi
          if [ "$service" = "ConsultationManagementService" ]; then dockerfile="ConsultationManagementService.API/Dockerfile"; fi
          if [ "$service" = "FacturationService" ]; then dockerfile="Facturation.API/Dockerfile"; fi
          if [ "$service" = "ReportingService" ]; then dockerfile="Reporting.API/Dockerfile"; fi
          if [ "$service" = "NotificationService" ]; then dockerfile="Notif.API/Dockerfile"; fi

          lowercase_service=$(echo "$service" | tr "[:upper:]" "[:lower:]")
          echo "Building $service..."
          docker build -t $DOCKER_REGISTRY/$lowercase_service:$DOCKER_IMAGE_TAG -f ./Services/$service/$dockerfile ./Services/$service
          docker push $DOCKER_REGISTRY/$lowercase_service:$DOCKER_IMAGE_TAG
        done
      '


docker_build_frontend:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $DOCKER_REGISTRY/Frontend:$DOCKER_IMAGE_TAG ./Frontend
    - docker push $DOCKER_REGISTRY/Frontend:$DOCKER_IMAGE_TAG

# ---------------- Deploy with Docker Compose ----------------
deploy:
  stage: deploy
  image: docker/compose:2.21.2
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml up -d --remove-orphans

