stages:
  - build
  - test
  - docker
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOCKER_REGISTRY: "$CI_REGISTRY/saas-clinic"
  DOCKER_IMAGE_TAG: "latest"

# ---------------- Build .NET projects ----------------
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - |
      for sln in Services/*/*.sln; do
        echo "Restoring and building $sln..."
        dotnet restore "$sln"
        dotnet build "$sln" --configuration Release
      done

# ---------------- Run tests ----------------
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - |
      for sln in Services/*/*.sln; do
        echo "Running tests for $sln..."
        dotnet test "$sln" --no-build --verbosity normal || exit 1
      done

# ---------------- Build & Push Docker images ----------------
docker_build_backend:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: "registry.gitlab.com/ayoubdammak/clinic-saas"
    DOCKER_IMAGE_TAG: "latest"
  script:
    - apk add --no-cache bash
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      bash -c '
        services=("AuthService" "ClinicManagementService" "DoctorManagementService" "PatientManagementService" "RDVManagementService" "ConsultationManagementService" "FacturationService" "ReportingService" "NotificationService")

        for service in "${services[@]}"; do
          # Définir le Dockerfile pour chaque service
          case "$service" in
            AuthService) dockerfile="Auth.API/Dockerfile" ;;
            ClinicManagementService) dockerfile="Clinic.API/Dockerfile" ;;
            DoctorManagementService) dockerfile="Doctor.API/Dockerfile" ;;
            PatientManagementService) dockerfile="PatientManagementService.API/Dockerfile" ;;
            RDVManagementService) dockerfile="RDV.API/Dockerfile" ;;
            ConsultationManagementService) dockerfile="ConsultationManagementService.API/Dockerfile" ;;
            FacturationService) dockerfile="Facturation.API/Dockerfile" ;;
            ReportingService) dockerfile="Reporting.API/Dockerfile" ;;
            NotificationService) dockerfile="Notif.API/Dockerfile" ;;
          esac

          # Forcer le nom du service en minuscules et enlever les caractères invalides
          lowercase_service=$(echo "$service" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9._-')

          echo "Building $service..."
          docker build -t "$DOCKER_REGISTRY/$lowercase_service:$DOCKER_IMAGE_TAG" -f "./Services/$service/$dockerfile" "./Services/$service"
          docker push "$DOCKER_REGISTRY/$lowercase_service:$DOCKER_IMAGE_TAG"
        done
      '


docker_build_frontend:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: "registry.gitlab.com/ayoubdammak/clinic-saas"
    DOCKER_IMAGE_TAG: "latest"
  script:
    - apk add --no-cache bash
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - |
      bash -c '
        lowercase_frontend=$(echo "Frontend" | tr "[:upper:]" "[:lower:]")
        echo "Building frontend image..."
        docker build -t "$DOCKER_REGISTRY/$lowercase_frontend:$DOCKER_IMAGE_TAG" ./Frontend
        docker push "$DOCKER_REGISTRY/$lowercase_frontend:$DOCKER_IMAGE_TAG"
      '

# ---------------- Deploy with Docker Compose ----------------
deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-cli-compose
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose -f docker-compose.yml pull
    - docker compose -f docker-compose.yml up -d --remove-orphans


