CREATE TABLE Cliniques (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Nom NVARCHAR(100) NOT NULL,
    Adresse NVARCHAR(200) NOT NULL,
    NumeroTelephone NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL,
    DateCreation DATETIME2 NOT NULL,
    SiteWeb NVARCHAR(MAX) NULL,
    Description NVARCHAR(MAX) NULL,
    Statut INT NOT NULL DEFAULT(0),
    TypeClinique INT NOT NULL DEFAULT(0)
);
