CREATE TABLE RendezVous (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PatientId UNIQUEIDENTIFIER NOT NULL,
    MedecinId UNIQUEIDENTIFIER NOT NULL,
    DateHeure DATETIME2 NOT NULL,
    Statut NVARCHAR(MAX) NOT NULL,
    Commentaire NVARCHAR(500) NOT NULL,
    DateCreation DATETIME2 NOT NULL DEFAULT(GETDATE())
);
